### ISSUE TITLE
The filter specifications are not displayed in the filter list (rules)

### ISSUE THREAD

**Issue by zonky2** [MetaModels/filter_range#15]
The filter specifications are not displayed in the filter list (rules) - I see only the ID

![screenshot_499](https://user-images.githubusercontent.com/1045318/54879991-2230ae80-4e40-11e9-9cac-009e918bb9b4.jpg)

**Comment by baumannsven** [comment]
Fixed in d7b70d75a1e01862c670056e271f072b31b69cb7
