### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by seaneble** [MetaModels/filter_range#3]
After installation of *filter_range* via Composer I cannot save any new filters with this type. The error message claims that there is no field ```dateformat``` in the filter table, although there is a DCA field in the mask.

As I found out, installing *filter_fromto* solves the issue, as the missing database field is provided therein. Could you please mark **filter_fromto** as a dependency of **filter_range**?

**Comment by stefanheimes** [comment]
Hi, 

thanks for the information. I change some elements of the filter based on the From-To-filter. Maybe i forgot some fields. Sorry for this. I will fix this as soon as possible.

**Comment by xantippe** [comment]
@seaneble kannst Du checken, ob der Fehler noch da ist...

**Comment by seaneble** [comment]
Based on what I can see in the source code there is still:

- a dca field of the name "dateformat"
- no such field in the `database.sql` file
- no dependency to filter_fromto in the `composer.json`

So I would regard this as not fixed. There also are no commits associated with the issue.

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@seaneble could you please have a final look at this and tell if your issue has been resolved?
