### ISSUE TITLE
add a selection for the type of filtering

### ISSUE THREAD

**Issue by zonky2** [MetaModels/filter_range#8]
Currently we have a merge of the two filter queries 
https://github.com/MetaModels/filter_range/blob/master/src/MetaModels/Filter/Setting/AbstractRange.php#L345-L356
with the following search result

`DB: ---------15---------20-----` the data of attribute 1 (=15) and 2 (=20)
we search with two values, e.g. ...
`S1: -----------16-----18-------` we have a hit
`S2: ------13----------18-------` we have a hit
`S3: -----------16----------22--` we have a hit
`S4: S1 OR S2 OR S3                  ` => the current behavior... "at minimum one value must be inside of range"
`S5: ------13---------------22--` we have a hit ("S1 inverse") [new]
`S6: S1 OR S5                          ` => new

Search "S1" must return a hit,  but so must also search  "S2" and "S3"?

The search "S5" is for example, if a trip is entered in the database and you are looking for a trip period in which a trip is included. 

May be we can add a selection for the type of filtering...

**Comment by zonky2** [comment]
short discussion with @discordier: we should create the four filter options as radio button list

**Comment by discordier** [comment]
For date fields, this depends on MetaModels/attribute_timestamp#31

**Comment by zonky2** [comment]
add in MM 2.2
